-- MySQL Script generated by MySQL Workbench
-- Wed Jan  8 20:27:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chatterbox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatterbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatterbox` DEFAULT CHARACTER SET utf8 ;
USE `chatterbox` ;

-- -----------------------------------------------------
-- Table `chatterbox`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatterbox`.`rooms` ;

CREATE TABLE IF NOT EXISTS `chatterbox`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatterbox`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatterbox`.`users` ;

CREATE TABLE IF NOT EXISTS `chatterbox`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `photo` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatterbox`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatterbox`.`messages` ;

CREATE TABLE IF NOT EXISTS `chatterbox`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contents` VARCHAR(160) NULL,
  `user_id` INT NULL,
  `room_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`user_id` ASC),
  INDEX `id_idx1` (`room_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chatterbox`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`room_id`)
    REFERENCES `chatterbox`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatterbox`.`friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatterbox`.`friends` ;

CREATE TABLE IF NOT EXISTS `chatterbox`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `friend_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
