-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 21:46:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chatterbox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatterbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatterbox` DEFAULT CHARACTER SET utf8 ;
USE `chatterbox` ;

-- -----------------------------------------------------
-- Table `chatterbox`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatterbox`.`rooms` ;

CREATE TABLE IF NOT EXISTS `chatterbox`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatterbox`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatterbox`.`users` ;

CREATE TABLE IF NOT EXISTS `chatterbox`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `photo` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatterbox`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatterbox`.`messages` ;

CREATE TABLE IF NOT EXISTS `chatterbox`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contents` VARCHAR(160) NULL,
  `user_id` INT NULL,
  `room_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatterbox`.`friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatterbox`.`friends` ;

CREATE TABLE IF NOT EXISTS `chatterbox`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `friend_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
